### ISSUE TITLE
No longer working?

### ISSUE THREAD

**Issue by Lashley93** [SwiftSmoothvZ/NitroPerks-Working-Version-#2]
Hi, no longer allows me to use any emoji

![image](https://user-images.githubusercontent.com/50780989/155010606-0a433b55-0caf-4d17-a082-0378637583df.png)
![image](https://user-images.githubusercontent.com/50780989/155010621-39809c29-0437-4b86-ac11-c75827a35dc2.png)
<img width="299" alt="image" src="https://user-images.githubusercontent.com/50780989/155010652-05f9849d-aa22-41ee-be20-897c8711c4ed.png">

**Comment by SwiftSmoothvZ** [comment]
Discord patched every free emoji/nitro plugins it doesn't work anymore
